name: hub_mqtt
description: A desktop Flutter project to query and dissect MQTT payloads into devices with attributes,values,commands etc
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.2.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  deep_pick: ^0.10.0
  json_view: ^0.4.0

  mqtt_client: ^9.7.4
  events_emitter: ^0.5.2
  jinja: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg